<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="W1651507" ignored="0" name="Test" tests="2" failures="1" timestamp="13 Apr 2020 19:57:49 GMT" time="38.237" errors="0">
  <testcase name="init" time="8.711" classname="testcases.FacebookLoginTestFail">
    <failure type="java.lang.Exception" message="Contact number error!!!">
      <![CDATA[java.lang.Exception: Contact number error!!!
at pages.FacebookLoginPage.assertLoginPageErrorMsg(FacebookLoginPage.java:139)
at testcases.FacebookLoginTestFail.init(FacebookLoginTestFail.java:22)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- init -->
  <testcase name="init" time="7.824" classname="testcases.FacebookLoginTestPass"/>
</testsuite> <!-- Test -->
